name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Verify Cypress Binary
        run: npx cypress install     

      - name: Install Mochawesome reporter
        run: npm install --save-dev cypress-mochawesome-reporter mochawesome mochawesome-merge mochawesome-report-generator
      
      - name: Set environment variables
        run: |
              echo "CYPRESS_VALID_USERNAME=${{ secrets.CYPRESS_VALID_USERNAME }}" >> $GITHUB_ENV
              echo "CYPRESS_VALID_PASSWORD=${{ secrets.CYPRESS_VALID_PASSWORD }}" >> $GITHUB_ENV
              echo "CYPRESS_BASE_URL=${{ secrets.CYPRESS_BASE_URL}}" >> $GITHUB_ENV

      # Generate test reports after run
      - name: Generate Mochawesome report
        run: |
              mkdir -p ./cypress/e2e/reports/mochawesome
              npx mochawesome-merge ./cypress/e2e/reports/mochawesome/*.json -o ./cypress/e2e/reports/mochawesome/mochawesome.json
              npx marge ./cypress/e2e/reports/mochawesome/mochawesome.json --reportDir ./cypress/e2e/reports/html --overwrite --inline
       
      - name: List reports directory
        run: ls -l ./cypress/e2e/reports/mochawesome/   

      - name: Run Cypress Tests in headless mode
        run: 
          npx cypress run --env CYPRESS_BASE_URL=${{ secrets.CYPRESS_BASE_URL}},CYPRESS_VALID_USERNAME=${{ secrets.CYPRESS_VALID_USERNAME }},CYPRESS_VALID_PASSWORD=${{ secrets.CYPRESS_VALID_PASSWORD }} --reporter cypress-mochawesome-reporter
       
      - name: Install WebKit Dependencies
        run: npx playwright install-deps webkit
        
      - name: Run Cypress Tests in Safari bowser headless mode
        run: 
          npx cypress run --browser webkit --env CYPRESS_BASE_URL=${{ secrets.CYPRESS_BASE_URL}},CYPRESS_VALID_USERNAME=${{ secrets.CYPRESS_VALID_USERNAME }},CYPRESS_VALID_PASSWORD=${{ secrets.CYPRESS_VALID_PASSWORD }} --reporter cypress-mochawesome-reporter
      
      - name: Run Cypress Tests in Headed Mode
        run: 
           npx cypress run --headed --env CYPRESS_VALID_USERNAME=${{ secrets.CYPRESS_VALID_USERNAME }},CYPRESS_VALID_PASSWORD=${{ secrets.CYPRESS_VALID_PASSWORD }}
 
      # Save Cypress screenshots and videos on failure
      - name: Upload Cypress Screenshots (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/

      - name: Upload Cypress Videos (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: ./cypress/e2e/reports/html
