name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Verify Cypress Binary
        run: npx cypress install     
      
      - name: Set environment variables
        run: |
              echo "CYPRESS_VALID_USERNAME=${{ secrets.CYPRESS_VALID_USERNAME }}" >> $GITHUB_ENV
              echo "CYPRESS_VALID_PASSWORD=${{ secrets.CYPRESS_VALID_PASSWORD }}" >> $GITHUB_ENV
                  
      # - name: Run Cypress Tests in headless mode
      #   run: npx cypress run

      - name: Run Cypress Tests in Headed Mode
        run: 
           npx cypress run --headed --env CYPRESS_VALID_USERNAME=${{ secrets.CYPRESS_VALID_USERNAME }},CYPRESS_VALID_PASSWORD=${{ secrets.CYPRESS_VALID_PASSWORD }}
 
      # Save Cypress screenshots and videos on failure
      - name: Upload Cypress Screenshots (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/

      - name: Upload Cypress Videos (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/
