name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Verify Cypress Binary
        run: npx cypress install     

      # - name: Run Cypress Tests
      #   run: npx cypress run

      - name: Run Cypress Tests in Headed Mode
        run: npx cypress run --headed

      # Save Cypress screenshots and videos on failure
      - name: Upload Cypress Screenshots (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/

      - name: Upload Cypress Videos (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/
